name: Backend CI/CD 

on:
  workflow_call:
    inputs:
      service-name:
        description: 'Name of the backend service'
        required: true
        type: string
      environment:
        description: 'Deployment environment (dev, test, prod)'
        required: true
        type: string
    secrets:
      dockerhub-username:
        description: 'DockerHub Username'
        required: true
      dockerhub-token:
        description: 'DockerHub Access Token'
        required: true
      sonar-token:
        description: 'SonarQube Token'
        required: true
      sonar-host-url:
        description: 'SonarQube Host URL'
        required: true
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout devops-configuration repo
        uses: actions/checkout@v3
        with:
          repository: entrega-devops-agosto-nicolas-banales/devops-configuration
          path: devops-configuration

      - name: Copy Dockerfile
        run: cp devops-configuration/dockerfiles/${{ inputs.service-name }}/Dockerfile .

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.service-name }}
            -Dsonar.organization=entrega-devops-agosto-nicolas-banales
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectBaseDir=./ 
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}

          
      - name: Run Tests
        run: mvn test

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.dockerhub-username }}/${{ inputs.service-name }}:${{ github.sha }}

      - name: Deploy to AWS
        if: success()
        run: |
          # Add commands to deploy to AWS using Terraform or AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
