name: Backend CI/CD 

on:
  workflow_call:
    inputs:
      service-name:
        description: 'Name of the backend service'
        required: true
        type: string
      environment:
        description: 'Deployment environment (dev, test, prod)'
        required: true
        type: string
    secrets:
      dockerhub-username:
        description: 'DockerHub Username'
        required: true
      dockerhub-token:
        description: 'DockerHub Access Token'
        required: true
      sonar-token:
        description: 'SonarQube Token'
        required: true
      sonar-host-url:
        description: 'SonarQube Host URL'
        required: true
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
      aws-session-token:
        description: 'AWS Session Token'
        required: true  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout devops-configuration repo
        uses: actions/checkout@v3
        with:
          repository: entrega-devops-agosto-nicolas-banales/devops-configuration
          path: devops-configuration

      - name: Copy Dockerfile
        run: cp devops-configuration/dockerfiles/${{ inputs.service-name }}/Dockerfile .

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven and Run Tests 
        run: mvn clean install --no-transfer-progress

      - name: Run SonarQube Analysis with Maven
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
          SONAR_HOST_URL: ${{ secrets.sonar-host-url }}
          SONAR_ORGANIZATION: entrega-devops-agosto-nicolas-banales
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar
          -Dsonar.projectKey=entrega-devops-agosto-nicolas-banales_${{ inputs.service-name }}
          -Dsonar.organization=entrega-devops-agosto-nicolas-banales
          -Dsonar.login=$SONAR_TOKEN
          -X -e
      
      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.dockerhub-username }}/${{ inputs.service-name }}:${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          
      - name: Terraform Init
        working-directory: devops-configuration/terraform
        run: terraform init
        
      - name: Terraform Apply
        working-directory: devops-configuration/terraform
        run: terraform apply -auto-approve -var "aws_access_key=${{ secrets.aws-access-key-id }}" -var "aws_secret_key=${{ secrets.aws-secret-access-key }}" -var "dockerhub_username=${{ secrets.dockerhub-username }}" -var "image_tag=${{ github.sha }}" -var 'service_names=["${{ inputs.service-name }}"]'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

