name: Deploy to S3

on:
  workflow_call:
    inputs:
      bucket-name:
        description: 'S3 Bucket Name'
        required: true
        type: string
      environment:
        description: 'Deployment environment (dev, test, prod)'
        required: true
        type: string
    secrets:
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
      aws-session-token:
        description: 'AWS Session Token'
        required: false 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-session-token: ${{ secrets.aws-session-token }}
        aws-region: us-east-1

    - name: Sync Files to S3
      run: aws s3 sync ./dist s3://${{ inputs.bucket-name }} --delete

