name: Deploy to S3

on:
  workflow_call:
    inputs:
      bucket-name:
        description: 'S3 Bucket Name'
        required: true
        type: string
      environment:
        description: 'Deployment environment (dev, test, prod)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Sync Files to S3
      run: aws s3 sync ./dist s3://${{ inputs.bucket-name }} --delete
